### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by ghost** [Stephan-S/AutoDrive#1]
Since the new Update of FS is public, I get an error in my Log when I am loading a game:

Error: Running LUA method 'loadSharedI3DFileFinished'.
*/My Games/FarmingSimulator2017/mods/AutoDrive/AutoDrive.lua:1325: bad argument #1 to 'pairs' (table expected, got nil)

Please fix this issue in your next update.

And many thanks for the great work, please never stop this project!! ;)

Greetings,
Klaas

**Comment by Stephan-S** [comment]
This should be fixed with 0.7.2. You can find it under releases. If you have time, feel free to try and comment. I wont be able to do so until Sunday or Monday

**Comment by ghost** [comment]
Great!

The new version runs perfectly!
Thanks for the fast reply ;)

- closed -
