### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by pops64** [Stephan-S/AutoDrive#11]
I see there is a import folder in the farmingsimulator folder. I was wondering how it works has there is no information on it(in english) or is it not even implemented at this time. Tried placing the export file directly in there. renamed the export to import. no errors in log. Thanks

**Comment by Anonymous-any** [comment]
Hi you don't have read somewhere it seem forgot where ^^, you have to move or copy the export file (without rename it) in the import folder, and you have to configure a key button related to ADimport command that is not assigned as default if I remember good that all.

**Comment by pops64** [comment]
Ok that makes sense I didn't look in the keybindings for the answer. And nothing is stated in the English tutorial about keybindings. Thanks a bunch :D

**Comment by stueja** [comment]
Sorry, but I can't find a key binding possibility for AD: Import. So. How can I import routes?
