### ISSUE TITLE
Reminder as requested in the comments on modhoster.com

### ISSUE THREAD

**Issue by damnedsky** [Stephan-S/AutoDrive#2]
**Hello Balu! Bellow is the conversation:**
Scai
Hello! Just tried your mod out and was initially wondering about your choice to use Directed Graphs but then I realized the need for them in turning scenarios. That is smart thinking! 
I really REALLY like your mod and I hope you are opened to suggestions: 
1. would you be able to make parts of the graph go both ways? I am asking because on narrow roads with no traffic and only 1 lane, I have to record the path twice even if I could use the same path both ways. For long stretches of road to record, maybe have a special REC button for both ways? and if we need to make just one segment both ways then we could use the Toggle Connection button: 1st press = activate 1 way connection, 2nd press = activate opposite way connection(optional), 3rd press = activate 2 way connection, 4th press = deactivate connection 
2. There should be some king of feedback when recalculating the paths. At the moment I press the button and nothing happens. There is no event telling me that the program "heard" my command to recalculate. Would you be able to print a text somewhere with "recalculating..." and change it to "Done recalculating" when it is done? 
3. not working with frontloader, I saw from your other comments that you are taking care of this, AWESOME! 
4. I saw that "canto silver" recommended some kind of destination table to choose from. Would it be easier to implement some kind of search based option like the console? Once you start typing letters in the name field and press TAB it switches between the locations that start with those letters. 

Again i want to say this is an AWESOME mod and I want to thank you for all the hard work! Cheers!
 
Balu_AutoDrive
Hi, thanks for your feedback and your kind words :-) 
Here are my thoughts on your points: 
1. You are right, this is especially true on many mod maps which consist of much more narrow roads. But you really have to be careful with that because if multiple vehicles are driving the chance of them getting stuck in traffic gets really high. I might create an input option and a slightly modified recording icon to show that this mode is activated but i dont think it should be readily accessible via the hud :D 
2. Already done. Although it's just a text feedback updating the percentages and the hud icon turning red. A real loading bar would obviously be nicer :-) 
3. Yep, done 
4. As a programmer and regular linux user i really like this idea, but to be honest I dont see many users actually using it :D 

Just to remind me of 1+4, please feel free to open up an issue on my github site, so I wont forget it :-)

**Comment by Slapyurmomma** [comment]
I also would love to see #1 implemented into the mod. Other than that i love the mod and can't wait for future updates/features.

**Comment by Stephan-S** [comment]
I started implementing 1 and 4. Please have a look at release 1.0.2. You can switch to the dual recording by clicking the record button twice.
Entering destinations is now possible by clicking on the current destination text and start typing. You can switch through possible destinations with TAB and hit "Enter" to select the current destination.
Have fun :-)
