### ISSUE TITLE
Suggestions, ideas, optimizations

### ISSUE THREAD

**Issue by DeckerMMIV** [Stephan-S/AutoDrive#4]
If I may suggest some things for the script-code:

\- Try to not store 'all decimals of floating point values' for waypoints in the XML file. I would guess that the X/Y/Z resolution with zero or max one decimal will suffice.
`string.format("%.1f", 545.323)` -> `545.3`.

\- Maybe not store the Y value at all? Since it is "the height", it could be runtime calculated as an 'offset above the terrain'. (_well.. at bridges and at other "hidden lower terrain" it may look weird, but it will reduce the amount of data needed to store._)

\- There are `getXMLBool()`/`setXMLBool()` methods, so you can avoid string-comparing against "true" and "false".
More of those XML reading/writing methods can be found at https://gdn.giants-software.com/documentation_scripting.php?version=engine&category=15&function=229

\- You most likely have considered it, but I just want to suggest that the 'recalculating routes'-loop (and if possible the 'dijkstra' algorithm) should be "split up" into smaller executions, where only "one at a time" is executed per game-engine frame-update, which could make the game more responsive.

I know that this will not be an easy task, trying to change a "single-executed blocking algorithm" into multiple smaller parts.

A quick suggestion could be to fill an array of 'functions', where each 'function' calculates only one mapMarker id. - Then in the `updateTick()` it would execute only first element from the array and then remove it.

Example / pseudo-code:
```
    self.pendingTasks = {}

function MyMod:updateTick(dt)
  if next(self.pendingTasks) then
    -- When there are still execution-tasks pending
    -- Pop the first element and execute it
    local method = self.pendingTasks[1]
    method()  -- Execute the 'small task' function - anonymous method/lambda/closure
    table.remove(self.pendingTasks, 1)

  elseif true == needRecalculation then
    -- Starting a new calculation, which is going to be split into several smaller tasks
    needRecalculation = false

    -- Add each required 'small task' to the array, without executing them at this moment
    for i, marker in pairs(markers) do
      table.insert(
        self.pendingTasks
        , 
        function()  -- A single "task" - anonymous method/lambda/closure
          local value = MyMod:dijkstra(mapWaypoints, marker.id)
          for j,p in pairs(mapWaypoints) do
             -- etc...
          end
        end
      )
    end

  end
end
```

**Comment by Stephan-S** [comment]
Hey Decker, thanks for your suggestion.
The biggest chunk of work is the seperation of the recalculation loop. This was already implemented when you wrote this comment :-)
For the tips with the xml files: You are right this can still be optimized, but it`s not really a significant factor. So I will see if I get to do it some time
