### ISSUE TITLE
Dedicated Server Fehler.

### ISSUE THREAD

**Issue by p4r4d0xs** [Stephan-S/AutoDrive#6]
Moin moin,
wir haben ein problem auf unserem Dedicated Server, undzwar wenn ich Connecte bekomme ich diese fehlermeldung 

Requesting waypoints
Warning: Could not decrypt received packet.

dann stürzt das Spiel ab.

**Comment by Dzi4d3k** [comment]
Well, I got the same when there is no waypoints recorded for map on single player.

BTW, is it possible to add recording functionality on MP, dedicated server especially?

**Comment by p4r4d0xs** [comment]
Our Dedicated Server is Hosted in a Private Home Server by a friend, if he connect from his network he can play but if his Brother or Me Connect from Outside we get this problem.
Before we Play the Map in SP an Uploaded it on the Server.

**Comment by Dzi4d3k** [comment]
Maybe you all need copy of recorded waypoints?

**Comment by p4r4d0xs** [comment]
How? I though the Server sends me the waypoints? 
I uploaded the Savegame on our Server, than the other Players only Downloaded the AutoDrive.zip and only the owner of the Dedicated Server in his homenetwork can play, the others get this error in the log.
Requesting waypoints
Warning: Could not decrypt received packet.
and than the game crash,

**Comment by p4r4d0xs** [comment]
> GIANTS Engine Runtime 7.0.0 (13785) 64bit (Build Date: Nov 21 2016)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Memory: 16266 MB
  OS: Windows NT 10.0 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 980
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 2560 x 1440
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Custom Very High
  View Distance Factor: 2.000000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 2.000000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 2.000000
  Foliage Density: 1.000000
  Volume Mesh Tessellation Factor: 0.500000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 10
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 8
Farming Simulator 17
  Version: 1.3.1.0 1.3.1RC10
  Available Languages: de
  Language: de
  Time: 2017-01-05 13:43:22
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: AutoDrive
Load mod: Bumb_Gewicht
Warning: Missing l10n for button movePanels in Bumb_Gewicht
Warning: Missing l10n for button moveSides in Bumb_Gewicht
Load mod: disableVehicleCameraCollision
Load mod: FS17_amazonePantera
Load mod: FS17_challengerMT700EFieldViper
Load mod: FS17_challengerMT775EStealth
Load mod: FS17_challengerMT800EFieldPython
Load mod: FS17_challengerMT900EFieldAnaconda
Load mod: FS17_DCK_RoundBalerAutoUnload
Load mod: FS17_deutzFahrCondimaster8331
Load mod: FS17_Fendt700er_Pack
Load mod: FS17_fendt900BlackBeauty
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_Fichtelberg
Load mod: FS17_flieglSTF25000VC
Load mod: FS17_flieglTMK266Bull
Load mod: FS17_flieglVFW10600
Load mod: FS17_ForRealModule01_CropDestruction
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_GiantsIsland17
Load mod: FS17_GrainStorage_placeable
Load mod: FS17_Grasdorf_Wennekamp
Load mod: FS17_holmerPack
Load mod: FS17_horschTitan34UW
Load mod: FS17_HT_50_Holmer
Load mod: FS17_itRunnerPack
Load mod: FS17_kirovetsK700A
Load mod: FS17_koeckerlingTrio300
Load mod: FS17_krampeBigBody900
Load mod: FS17_kroneBigXPack
Load mod: FS17_kuhnPrimor3570
Load mod: FS17_kuhnSitera3000
Load mod: FS17_kuhnVB2190
Load mod: FS17_kvernelandAB85
Load mod: FS17_lizardFloodLightTrailer
Load mod: FS17_lizardRoadRage
Load mod: FS17_marshallBC32
Load mod: FS17_marshallQM16
Load mod: FS17_marshallST1800
Load mod: FS17_masseyFerguson8737BlackEdition
Load mod: FS17_MB3D_ClaasJaguar800
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_Pack_Joskin_Wago_AUTO_BsM
Load mod: FS17_placeableRefillStation
Load mod: FS17_reckJumbo
Load mod: FS17_shedPackage
Load mod: FS17_SpeedPlayer
Load mod: FS17_starkIndustriesSCT635B
Load mod: FS17_UniversalLGS
Load mod: FS17_vaederstadRapid300
Load mod: FS17_vaederstadTopDown500
Load mod: FS17_valtraTSeriesCowEdition
Load mod: FS17_valtraTSeriesWREdition
Load mod: FS17_veenhuisW400
Load mod: FS17_WoodChipStorage_MachineryShedPLACEABLE
Load mod: Inspect17
Load mod: ZetorCrystal12045byAgrarteamWW
  Register vehicle type: Bumb_Gewicht.bumbGewicht
Script loaded: BalerAutoUnload.lua (v1.0.2.21)
  Register vehicle type: FS17_Fendt700er_Pack.fendt700Vario
  Register vehicle type: FS17_Grasdorf_Wennekamp.Grasdorf
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
  Register vehicle type: FS17_lizardFloodLightTrailer.lizardFloodLightTrailer
  Register vehicle type: FS17_Pack_Joskin_Wago_AUTO_BsM.transportTrailerUAL
  Register vehicle type: FS17_reckJumbo.SilageDistributor
Mod Loaded: Speed-Player
dataS/cameraPath01.i3d (0.09) ms
dataS/cameraPath02.i3d (0.09) ms
dataS/cameraPath03.i3d (0.07) ms
data/sky/skyUS_day_night.i3d (10.68) ms
data/sky/rain.i3d (1.58) ms
data/sky/hail.i3d (1.01) ms
data/sky/dust.i3d (0.90) ms
data/maps/map01.i3d (6943.18) ms
data/objects/basketball/basketball.i3d (2.73) ms
Map title: Goldcrest Valley
Savegame location via index: C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame7
map Goldcrest_Valley was loaded
--- loading AutoDrive mod
Disabled withering
data/vehicles/steerable/caseIH/caseIH1660.i3d (46.26) ms
AD: Loading xml file from init config
AD: Finished loading xml from memory
AD: creating xml file at C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame7/AutoDrive_config.xml
Loading from init file
AD: Loaded Waypoints: 6713
AD: Routes are already calculated
AD: creating xml file at C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame7/AutoDrive_config.xml
AutoDrive mod inserted into Vehicle Camera
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (33.95) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (37.33) ms
data/vehicles/tools/kuhn/kuhnCultimerL300.i3d (65.77) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (47.06) ms
data/vehicles/tools/greatPlains/gp3P1006NT.i3d (21.72) ms
data/vehicles/trailers/metaltech/db8000.i3d (108.90) ms
data/vehicles/steerable/lizard/lizardPickupRodeo.i3d (27.98) ms
data/placeables/shelters/storageShelter02.i3d (10.97) ms
data/placeables/shelters/storageShelter01.i3d (12.65) ms
data/placeables/shelters/vehicleShelter.i3d (7.66) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (5.57) ms
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (2.48) ms
data/objects/pallets/fertilizerTank.i3d (3.23) ms
data/vehicles/train/locomotive.i3d (87.42) ms
data/vehicles/train/wagonTimber.i3d (46.80) ms
data/vehicles/train/wagonWoodChips.i3d (47.16) ms
data/vehicles/train/wagonGrain.i3d (50.90) ms
data/vehicles/train/wagonSugarbeets.i3d (48.46) ms
dataS2/character/player/player01.i3d (298.82) ms
AD: Set to not recalculating routes
mod Deleted: Speed-Player
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 980
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 2560 x 1440
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Custom Very High
  View Distance Factor: 2.000000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 2.000000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 2.000000
  Foliage Density: 1.000000
  Volume Mesh Tessellation Factor: 0.500000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 10
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 8
Farming Simulator 17
  Version: 1.3.1.0 1.3.1RC10
  Available Languages: de
  Language: de
  Time: 2017-01-05 13:52:22
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: AutoDrive
Load mod: Bumb_Gewicht
Warning: Missing l10n for button movePanels in Bumb_Gewicht
Warning: Missing l10n for button moveSides in Bumb_Gewicht
Load mod: disableVehicleCameraCollision
Load mod: FS17_amazonePantera
Load mod: FS17_challengerMT700EFieldViper
Load mod: FS17_challengerMT775EStealth
Load mod: FS17_challengerMT800EFieldPython
Load mod: FS17_challengerMT900EFieldAnaconda
Load mod: FS17_DCK_RoundBalerAutoUnload
Load mod: FS17_deutzFahrCondimaster8331
Load mod: FS17_Fendt700er_Pack
Load mod: FS17_fendt900BlackBeauty
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_Fichtelberg
Load mod: FS17_flieglSTF25000VC
Load mod: FS17_flieglTMK266Bull
Load mod: FS17_flieglVFW10600
Load mod: FS17_ForRealModule01_CropDestruction
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_GiantsIsland17
Load mod: FS17_GrainStorage_placeable
Load mod: FS17_Grasdorf_Wennekamp
Load mod: FS17_holmerPack
Load mod: FS17_horschTitan34UW
Load mod: FS17_HT_50_Holmer
Load mod: FS17_itRunnerPack
Load mod: FS17_kirovetsK700A
Load mod: FS17_koeckerlingTrio300
Load mod: FS17_krampeBigBody900
Load mod: FS17_kroneBigXPack
Load mod: FS17_kuhnPrimor3570
Load mod: FS17_kuhnSitera3000
Load mod: FS17_kuhnVB2190
Load mod: FS17_kvernelandAB85
Load mod: FS17_lizardFloodLightTrailer
Load mod: FS17_lizardRoadRage
Load mod: FS17_marshallBC32
Load mod: FS17_marshallQM16
Load mod: FS17_marshallST1800
Load mod: FS17_masseyFerguson8737BlackEdition
Load mod: FS17_MB3D_ClaasJaguar800
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_Pack_Joskin_Wago_AUTO_BsM
Load mod: FS17_placeableRefillStation
Load mod: FS17_reckJumbo
Load mod: FS17_shedPackage
Load mod: FS17_SpeedPlayer
Load mod: FS17_starkIndustriesSCT635B
Load mod: FS17_UniversalLGS
Load mod: FS17_vaederstadRapid300
Load mod: FS17_vaederstadTopDown500
Load mod: FS17_valtraTSeriesCowEdition
Load mod: FS17_valtraTSeriesWREdition
Load mod: FS17_veenhuisW400
Load mod: FS17_WoodChipStorage_MachineryShedPLACEABLE
Load mod: Inspect17
Load mod: ZetorCrystal12045byAgrarteamWW
  Register vehicle type: Bumb_Gewicht.bumbGewicht
Script loaded: BalerAutoUnload.lua (v1.0.2.21)
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
  Register vehicle type: FS17_lizardFloodLightTrailer.lizardFloodLightTrailer
  Register vehicle type: FS17_Pack_Joskin_Wago_AUTO_BsM.transportTrailerUAL
Mod Loaded: Speed-Player
dataS/cameraPath01.i3d (0.10) ms
dataS/cameraPath02.i3d (0.10) ms
dataS/cameraPath03.i3d (0.07) ms
data/sky/skyUS_day_night.i3d (10.01) ms
data/sky/rain.i3d (1.70) ms
data/sky/hail.i3d (1.10) ms
data/sky/dust.i3d (0.84) ms
data/maps/map01.i3d (1450.95) ms
data/objects/basketball/basketball.i3d (2.59) ms
Map title: Goldcrest Valley
Savegame location via index: C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame0
map Goldcrest_Valley was loaded
--- loading AutoDrive mod
Enabled withering
Joined network game (26)
data/vehicles/steerable/caseIH/caseIH1660.i3d (46.10) ms
AD: Loading xml file from init config
AD: Finished loading xml from memory
AD: creating xml file at C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame0/AutoDrive_config.xml
Loading from init file
AD: Loaded Waypoints: 6713
AD: Routes are already calculated
AD: creating xml file at C:/Users/Patrick/Documents/My Games/FarmingSimulator2017/savegame0/AutoDrive_config.xml
AutoDrive mod inserted into Vehicle Camera
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (30.76) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (32.51) ms
data/vehicles/tools/kuhn/kuhnCultimerL300.i3d (16.89) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (43.80) ms
data/vehicles/tools/greatPlains/gp3P1006NT.i3d (21.02) ms
data/vehicles/trailers/metaltech/db8000.i3d (26.31) ms
data/vehicles/steerable/lizard/lizardPickupRodeo.i3d (25.89) ms
data/placeables/shelters/storageShelter01.i3d (5.47) ms
data/placeables/shelters/storageShelter02.i3d (2.50) ms
data/placeables/shelters/vehicleShelter.i3d (1.72) ms
data/vehicles/train/locomotive.i3d (20.54) ms
data/vehicles/train/wagonTimber.i3d (10.18) ms
data/vehicles/train/wagonWoodChips.i3d (11.33) ms
data/vehicles/train/wagonGrain.i3d (11.15) ms
data/vehicles/train/wagonSugarbeets.i3d (10.90) ms
dataS2/character/player/player01.i3d (297.67) ms
Disabled withering
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (5.22) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (2.35) ms
data/objects/pallets/fertilizerTank.i3d (3.00) ms
Requesting waypoints
Received Event
Receiving waypoints
AD: Loaded Waypoints: 6713
AD: Loaded Destinations: 25
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.

>

**Comment by Dzi4d3k** [comment]
Maybe it should. I'm not sure, we have to wait for author's answer. Though it is worth trying to share xml file with waypoints and check if it is working as for the owner of Dedi Server.

Edits:
Looks like it see waypoints. So there must be an error in code then.

**Comment by p4r4d0xs** [comment]
you mean AutoDrive_config.xml? Or which xml you mean? 
po polsku bylo by troche lzej :P ale zeby kazdy zrozumial to bedziemy dalej to eng pisac

**Comment by Stephan-S** [comment]
Yes, thats whats supposed to happen. The server send the waypoints to the clients. Im trying to figure out why this error occurs. It hasnt happened to me yet and I can only try reproducing it next week when im home from vacation :-)
Your config seems to placed correctly at the server side since the correct amount of waypoints is received. Ill have a look at it as soon as i can.

**Comment by Stephan-S** [comment]
What might help would be the server log if you could also post it here. I would like to know if he only send the message once or if he tries resending it over and over again what the errors on the client side suggest

**Comment by p4r4d0xs** [comment]
> GIANTS Engine Runtime 7.0.0 (13785) 64bit (Build Date: Nov 21 2016)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Xeon(R) CPU           X3430  @ 2.40GHz
  Memory: 16374 MB
  OS: Windows NT 6.3 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard disabled
  Mouse disabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: NULL
Render System
  Driver: NULL
  NullConsoleDevice initialized
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Low (forced)
  View Distance Factor: 0.750000
  Shadow Quality: 0.000000 Size: 1 Filter-Size: 4
  Shader Quality: 0
  Skip Mipmaps: 1
  LOD Distance Factor: 0.750000
  Terrain LOD Distance Factor: 0.750000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.000000
  Foliage Density: 0.300000
  Volume Mesh Tessellation Factor: 1.500000
  Tyre Tracks Segments Factor: 0.500000
  Max. Number of Shadow Lights: 0
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 0
Farming Simulator 17 (Server)
  Version: 1.3.1.0 1.3.1RC10
  Available Languages: de
  Language: de
  Time: 2017-01-05 13:53:20
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: AutoDrive
Load mod: Bumb_Gewicht
Warning: Missing l10n for button movePanels in Bumb_Gewicht
Warning: Missing l10n for button moveSides in Bumb_Gewicht
Load mod: disableVehicleCameraCollision
Load mod: FS17_amazonePantera
Load mod: FS17_challengerMT700EFieldViper
Load mod: FS17_challengerMT775EStealth
Load mod: FS17_challengerMT800EFieldPython
Load mod: FS17_challengerMT900EFieldAnaconda
Load mod: FS17_DCK_RoundBalerAutoUnload
Load mod: FS17_deutzFahrCondimaster8331
Load mod: FS17_fendt900BlackBeauty
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_flieglSTF25000VC
Load mod: FS17_flieglTMK266Bull
Load mod: FS17_flieglVFW10600
Load mod: FS17_ForRealModule01_CropDestruction
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_GrainStorage_placeable
Load mod: FS17_holmerPack
Load mod: FS17_horschTitan34UW
Load mod: FS17_HT_50_Holmer
Load mod: FS17_itRunnerPack
Load mod: FS17_kirovetsK700A
Load mod: FS17_koeckerlingTrio300
Load mod: FS17_krampeBigBody900
Load mod: FS17_kroneBigXPack
Load mod: FS17_kuhnPrimor3570
Load mod: FS17_kuhnSitera3000
Load mod: FS17_kuhnVB2190
Load mod: FS17_kvernelandAB85
Load mod: FS17_lizardFloodLightTrailer
Load mod: FS17_lizardRoadRage
Load mod: FS17_marshallBC32
Load mod: FS17_marshallQM16
Load mod: FS17_marshallST1800
Load mod: FS17_masseyFerguson8737BlackEdition
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_Pack_Joskin_Wago_AUTO_BsM
Load mod: FS17_placeableRefillStation
Load mod: FS17_shedPackage
Load mod: FS17_SpeedPlayer
Load mod: FS17_starkIndustriesSCT635B
Load mod: FS17_UniversalLGS
Load mod: FS17_vaederstadRapid300
Load mod: FS17_vaederstadTopDown500
Load mod: FS17_valtraTSeriesCowEdition
Load mod: FS17_valtraTSeriesWREdition
Load mod: FS17_veenhuisW400
Load mod: FS17_WoodChipStorage_MachineryShedPLACEABLE
Load mod: Inspect17
Load mod: ZetorCrystal12045byAgrarteamWW
Started network game (10823)
  Register vehicle type: Bumb_Gewicht.bumbGewicht
Script loaded: BalerAutoUnload.lua (v1.0.2.21)
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
  Register vehicle type: FS17_lizardFloodLightTrailer.lizardFloodLightTrailer
  Register vehicle type: FS17_Pack_Joskin_Wago_AUTO_BsM.transportTrailerUAL
Mod Loaded: Speed-Player
dataS/cameraPath01.i3d (0.16) ms
dataS/cameraPath02.i3d (0.15) ms
dataS/cameraPath03.i3d (0.11) ms
data/sky/skyUS_day_night.i3d (170.15) ms
data/sky/rain.i3d (20.91) ms
data/sky/hail.i3d (15.15) ms
data/sky/dust.i3d (12.67) ms
data/maps/map01.i3d (12509.99) ms
data/objects/basketball/basketball.i3d (46.53) ms
Map title: Goldcrest Valley
Savegame location: C:/Users/Administrator/Documents/My Games/FarmingSimulator2017/savegame7
map Goldcrest_Valley was loaded
--- loading AutoDrive mod
Disabled withering
data/vehicles/steerable/caseIH/caseIH1660.i3d (584.66) ms
AD: Loading xml file from C:/Users/Administrator/Documents/My Games/FarmingSimulator2017/savegame7/AutoDrive_config.xml
AD: Loaded Waypoints: 6713
AD: Routes are already calculated
AutoDrive mod inserted into Vehicle Camera
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (361.28) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (330.50) ms
data/vehicles/tools/kuhn/kuhnCultimerL300.i3d (267.19) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (402.61) ms
data/vehicles/tools/greatPlains/gp3P1006NT.i3d (195.48) ms
data/vehicles/trailers/metaltech/db8000.i3d (288.91) ms
data/vehicles/steerable/lizard/lizardPickupRodeo.i3d (320.85) ms
data/placeables/shelters/storageShelter01.i3d (27.14) ms
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (85.89) ms
data/objects/pallets/fertilizerTank.i3d (53.22) ms
data/placeables/shelters/storageShelter02.i3d (25.63) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (30.18) ms
data/placeables/shelters/vehicleShelter.i3d (20.42) ms
data/vehicles/train/locomotive.i3d (239.25) ms
data/vehicles/train/wagonTimber.i3d (110.97) ms
data/vehicles/train/wagonWoodChips.i3d (92.00) ms
data/vehicles/train/wagonGrain.i3d (109.17) ms
data/vehicles/train/wagonSugarbeets.i3d (112.64) ms
dataS2/character/player/player01.i3d (717.11) ms
Patrick (1) joined the game
Broadcasting waypoints
Received Event
Receiving request for broadcasting waypoints
Broadcasting waypoints

> 
Game.log

**Comment by p4r4d0xs** [comment]
i try to connect via VPN to the server and try to connect in the game, maybe there is a problem with sending the waypoints with our Server.

**Comment by Stephan-S** [comment]
Hey, I saw that the server tries sending the waypoints twice. maybe this could cause problems. I have prevented this now and updated the mod to 1.0.7. When you have the time I would appreciate if you could test it, since i cant right now :-)

**Comment by p4r4d0xs** [comment]
where i can download it?

**Comment by p4r4d0xs** [comment]
server log

> Patrick (1) joined the game
Received Event
Receiving request for broadcasting waypoints
Broadcasting waypoints
Warning: Send called with unknown target address.

> 

my log

> Requesting waypoints
Warning: Could not decrypt received packet.
Warning: Could not decrypt received packet.

> 

if you came back from your vaccation, you can try to connect on our Server and test it! :)

**Comment by p4r4d0xs** [comment]
so with V1.0.7 its works now! After 5 Minutes of heavy lags and FPs drops from 60 - 0 its works, i think its a Client side problem. 
but my log is full with this issue
Warning: Could not decrypt received packet.

**Comment by Stephan-S** [comment]
hm, ok. its normal that the game will lag for about 5 seconds when you receive the waypoints. I cant really change that. but it should not lag for 5 minutes. But im glad that it at least works :D

**Comment by p4r4d0xs** [comment]
yes you wrote it in the description! :) But its only works, when i start a new game and only with the AutoDrive Mod on the Server.

**Comment by p4r4d0xs** [comment]
ok this dont work anymore. If your back from vaccation we can try this on our Dedicated Server
