### ISSUE TITLE
Mods vs. repositories

### ISSUE THREAD

**Issue by Dzi4d3k** [Stephan-S/AutoDrive#7]
Just a curiosity - why don't you create separate repositories for your 3 mods like others do. I believe it will be more clear for people who, like me, following you work :-)

**Comment by Stephan-S** [comment]
Because it is convenient for me, to have it all in one place. I might change that in time, but for now I do not want to break the existing links I shared for the Global Market mod in some forums. So for new mods you can probably expect a new repository :-)
