### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by kojote006** [Stephan-S/AutoDrive#8]
Error: Running LUA method 'update'.
D:/Dokumente/My Games/FarmingSimulator2017/mods/AutoDrive/AutoDrive.lua:3921: attempt to index a nil value

Aufgetreten mit der Version 1.0.8 auf Goldcrest Valley

**Comment by Stephan-S** [comment]
Should be fixed in 1.1.3. Thanks for the info
